### ISSUE TITLE
Add a debugging library that can be set to to dev mode for logs

### ISSUE THREAD

**Issue by dckesler** [celo-org/react-celo#226]
We can add a debug log library to many of the events and actions that can be enabled to help developers see what things are going on.

**Comment by aaronmgdr** [comment]
I dont think a library is needed just a little function that only runs console.info when DEBUG == true

**Comment by dckesler** [comment]
Yeah that's fine too

**Comment by fbaud** [comment]
we have not transitionned to react-celo, yet. We will probably migrate in the future since we are using react.
we are using contractkit, could the log function be implemented in @celo/contractkit so that we can use it before then?

here are a few functions that would be neat:
- activation/deactivation of logs so that we base on our on business logic the logging (I don't know if contractkit has a setDebugMode function that would be a second best if logging is automatic for DEBUG == true)
- possibility to register a callback function that would be called for any log event
- possibility to request buffering of these specific log events to dump one clean journal of a session to share with others (if we have a callback, we can also do that on our side with no problem)

of course, we don't need all these functions right away, function 1 is the only one necessary to start with

**Comment by fbaud** [comment]
> I dont think a library is needed just a little function that only runs console.info when DEBUG == true

Following the Log4j mishap, I'm a believer in avoiding using external libraries and keeping logs simple unless a program needs very specific features. Default logging to the console, or ability to define an alternate outstream is often enough. Timing of logs is the main feature I would see as a really useful extra
